[package]
name = "tui-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
crossterm.workspace = true
termion.workspace = true
serde.workspace = true
thiserror.workspace = true
once_cell.workspace = true
anyhow.workspace = true

[lints.rust]
unsafe_code = "forbid"
